@startuml "Chińczyk"

abstract Player{
    protected String name;
    protected Color colorOfCounters;
    
    public Player(String name);
    public String getName();
    public Color getColor();
    public void setName(String name);
    public void setColorOfCounters(Color color);

    public abstract int chooseCounter(Board board);
    public abstract boolean ifUser();
}

class Bot{

}

class User{

}

class GameEngine{
    private Player[] players;
    private GameFrame gameFrame;
    private Board board;
    private int playersIterator = 0;

    public GameEngine();
    public void run();
    public boolean game(int currentPlayer);
    public void collide(Color whichGroup, int position);
    public boolean ifPlayerWon(Color playerColor);
    public void exitGame();
}

abstract GameFrame{
    {field} public final Random RANDOM = new Random();
    {field} public ArrayList<Integer> eyes = new ArrayList<>(4);

    public void clearBoard();
    public void viewGame(Board board, Player[] players);
    public void viewBoard(Board board, Player player);
    public void viewWinner(Player player);
    public ArrayList<Counter> viewAvalibleCounters
    (Player player, int whichPlayer, int howManyEye, Board board);
    public void viewCounters(Board board);
    public int viewDieAnimation();
    public void viewExitInfo();
    default public int draw();
}

class GameFrameAPI{
    private GameEngine gameEngine;
    {field} private Map<Color, JButton[]> houseFields;
    {field} private Map<Color, JButton[]> baseFields;
    {field} private ArrayList<JButton> fields;
    
    private ArrayList<Counter> avalibleCounters;
    
    private char[] roadDirections;
    
    private int[] howManyButtons = {2, 4, 4};
    private int playerDraw;
}

class InitValue{
    {field} public static final Map<String, Color> COUNTER_COLORS;
    {field} public static final int BOARD_SIZE = 40;
}

class OptionFrame{
    {field} protected static StartOptionPane startOptionPane;
}

class StartOptionPane{
    private int usersAmount = 1;
    private PlayerInitPane[] playerInitPanes = new PlayerInitPane[4];
}

class PlayerInitPane{
    private static int paneCounter = 0;
    private int whichPane;
    private boolean ifUser;
}

class Main{
    public static void main(String args[]);
}

class Counter{
    protected int position;
    private int road = 0;
}

class Board{
    public final int[] outFields = { 32, 2, 12, 22 };
    {field} protected Map<Color, Counter[]> counters;
}

Bot "dziedziczy po" --|> Player
User "dziedziczy po" --|> Player

GameFrameAPI "dziedziczy po" -up-|> GameFrame

Player "1" --* "4" GameEngine

GameEngine "zawiera się w" --> Main
StartOptionPane "zawiera się w" --> OptionFrame
PlayerInitPane "1" --* "4" StartOptionPane
Counter "1" --* "16" Board
Board "zawiera się w" --> GameEngine
GameFrameAPI "zawiera się w" --> GameEngine
OptionFrame "jest wywoływany w" --> "run();" GameEngine

@enduml